config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'like/create'
  get 'comment/edit'
  resources :gossip, except: [:destroy] 
  resources :author
  resources :welcome, only: [:index, :show]
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :city 
  resources :sessions, only: [:new, :create, :destroy]
  resources :comment
  resources :like
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence: true
	validates :user_id, presence: true
	validates :gossip_id, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip

end

app/models/join_pm_recipient.rb
class JoinPmRecipient < ApplicationRecord
	belongs_to :private_message
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :user
	has_many :join_pm_recipients
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	has_many :users, through: :gossips
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :tags, through: :gossips
	has_many :private_messages
  	has_many :join_pm_recipients
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  	validates :first_name, presence: true
  	validates :last_name, presence: true
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="card bg-dark text-white">
  <img src=" https://psmag.com/.image/t_share/MTI3NTgyNTM1ODM1NDQ3MjY2/gossip-graphic.jpg" alt="..." height="350" >
  
  <div class="card-img-overlay">
    <center> 
    <h5 class="card-title">
      <h1 class="display-3" > <font color="blue" > Welcome!</font> <%= params[:first_name] %></h1> </h5>
    <p class="card-text"> <font size="6" color="blue"> Ici c'est notre super site de potins, il est chouette, non ?. </font></p>
<a class="btn btn-primary" <%= link_to "Soumettre un Gossip", new_gossip_path%> </a>
</center> 
  </div>
</div>

<p>
  
</p> 
<center> 
<h2> <font color="blue"> All gossips </font> </h2>
</center>
<p>
  
</p>
<section>
<div class="row">
<%Gossip.all.each do |gossip|%>
<div class="col-sm">
  
          <div class="col-lg-4">
            <img class="rounded-circle" src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" alt="Generic placeholder image" width="140" height="140">
            <div class="card-header">
     <%= link_to "#{User.find(gossip.user_id).first_name} #{User.find(gossip.user_id).last_name}", author_path(gossip.user_id), :class =>"text-muted p-0"%>
        </div>
            <p><%=gossip.title%></p>
            <p><a class="btn btn-primary" <%= link_to "Lire", gossip_path(gossip.id)%> </a></p>
      </footer>
    </blockquote>
  </div>
</div>

<%end%>
</div>
</section>

app/views/welcome/show.html.erb
<div class="card text-center mb-3">
  <div class="card-body">
    <h5 class="card-title font-weight-bold">BIENVENUE <%=params[:id]%> !</h5>
    <p class="card-text">Ici c'est notre super site de potins, il est chouette, non ?</p>
    <a class="btn btn-dark" <%= link_to "Soumettre un Gossip", new_gossip_path%></a>  </div>
</div>

<section>
<div class="card-deck">
<%Gossip.all.each do |gossip|%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Gossip #<%=gossip.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=gossip.title%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
      	<p><%=User.find(gossip.user_id).first_name%> <%=User.find(gossip.user_id).last_name%></p>
      	<a class="btn btn-dark" <%= link_to "Voir", gossip_path(gossip.id)%></a>
      </div>
      </footer>
    </blockquote>
  </div>
</div>
</div>
<%end%>
</div>
</section>