config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'like/create'
  get 'comment/edit'
  resources :gossip, except: [:destroy] 
  resources :author
  resources :welcome, only: [:index, :show]
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :city 
  resources :sessions, only: [:new, :create, :destroy]
  resources :comment
  resources :like
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence: true
	validates :user_id, presence: true
	validates :gossip_id, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip

end

app/models/join_pm_recipient.rb
class JoinPmRecipient < ApplicationRecord
	belongs_to :private_message
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :user
	has_many :join_pm_recipients
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	has_many :users, through: :gossips
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :tags, through: :gossips
	has_many :private_messages
  	has_many :join_pm_recipients
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  	validates :first_name, presence: true
  	validates :last_name, presence: true
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    def new
  	Gossip.new
  end
  def create
  	Gossip.create
  end

  def show
    @user=User.find(params[:id])
    @gossips=Gossip.where(user_id:params[:id])
  end

  def index
    
  end

  def edit
    
  end

  def update
    
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/author/show.html.erb
<div class="card">
  <div class="card-header font-weight-bold">
    Author #<%=params[:id]%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= User.find(params[:id]).first_name%> <%= User.find(params[:id]).last_name%></h5>
    <div class="card-text">
    	<p>email address : <%= User.find(params[:id]).email%></p>
    	<p>Age : <%= User.find(params[:id]).age%></p>
		<p>City : <%= link_to "#{@user.city.name}", city_path(@user.city.id), :class =>"text-dark p-0"%></p>
		<p>ZIP Code : <%= User.find(params[:id]).city.zip_code%></p>
		<p>Membre depuis le : <%= User.find(params[:id]).created_at.to_date%></p>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header mb-3">
    <% if Gossip.where(user_id:params[:id]).size == 0 %>
    <p><%= User.find(params[:id]).first_name%> n'a pas encore écrit de gossip</p>
    <% else %>
    <p><%= User.find(params[:id]).first_name%> a écrit le(s) <%=Gossip.where(user_id:params[:id]).size%> gossip(s) suivant(s) :</p>
    <%end%>
   </div>
<div class="card-deck">
<%Gossip.where(user_id:params[:id]).each do |gossip|%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Gossip #<%=gossip.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=gossip.title%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
      	<p><%=User.find(gossip.user_id).first_name%> <%=User.find(gossip.user_id).last_name%></p>
      	<a class="btn btn-dark" <%= link_to "Voir", gossip_path(gossip.id)%></a>
      </div>
      </footer>
    </blockquote>
  </div>
</div>
</div>
<%end%>
</div>
</div>